before_commands:
    - "composer install --prefer-source"

filter:
    excluded_paths:
        - tests/
        - vendor/
        - specs/

checks:
    php:
        code_rating: true
        duplication: true

