language: php

php: [5.6, 7, hhvm]

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_script: travis_retry composer install --no-interaction

script: 
  - vendor/bin/phpspec run -fpretty -v
  - vendor/bin/phpunit
  - vendor/bin/behat -fprogress
