language: php

matrix:
  include:
    - php: 5.6
      env: SYMFONY_VERSION='2.8.*'
    - php: 7.0
      env: SYMFONY_VERSION='3.0.*'

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer self-update
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --no-update "symfony/symfony:${SYMFONY_VERSION}"; fi;

before_script:
  - travis_retry composer install --no-interaction

script:
  - vendor/bin/phpspec run -fpretty -v
  - vendor/bin/phpunit
  - vendor/bin/behat -fprogress
